"""
MedBios AI — Clinical Report Generator
Produces structured physician-ready clinical summaries.
"""
import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def generate_clinical_summary(analysis: dict) -> dict:
    """
    Generate a structured clinical summary from the full analysis pipeline output.
    
    Input: analysis dict with keys: lab_values, insights, risk_scores, evidence_chains, etc.
    Output: Structured report dict ready for rendering.
    """
    lab_values = analysis.get("lab_values", [])
    insights = analysis.get("insights", [])
    risk_scores = analysis.get("risk_scores", {})
    patient_info = analysis.get("patient_info", {})
    document_type = analysis.get("document_type", "lab_report")
    differential = analysis.get("differential_diagnosis", [])

    # ── Abnormal findings ──
    abnormal_findings = []
    for lab in lab_values:
        status = lab.get("status", "normal")
        if status != "normal":
            abnormal_findings.append({
                "test": lab.get("test_name", lab.get("canonical_name", "Unknown")),
                "value": lab.get("value"),
                "unit": lab.get("unit") or lab.get("expected_unit", ""),
                "status": status,
                "reference_range": _format_range(lab.get("reference_min"), lab.get("reference_max")),
            })

    # Sort: critical first, then high/low
    severity_order = {"critical_low": 0, "critical_high": 0, "low": 1, "high": 1, "normal": 2}
    abnormal_findings.sort(key=lambda x: severity_order.get(x["status"], 2))

    # ── Clinical concerns ──
    clinical_concerns = []
    for insight in insights:
        clinical_concerns.append({
            "condition": insight["condition"],
            "confidence": insight["confidence"],
            "category": insight.get("category", ""),
        })

    # ── Recommendations ──
    recommendations = []
    seen_recs = set()
    for insight in insights:
        rec = insight.get("recommendation", "")
        if rec and rec not in seen_recs:
            seen_recs.add(rec)
            recommendations.append({
                "recommendation": rec,
                "priority": "high" if insight.get("confidence") == "high" else "routine",
                "related_to": insight["condition"],
            })

    # ── Build report ──
    report = {
        "title": "Patient Report Analysis",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "document_type": document_type,
        "disclaimer": (
            "DISCLAIMER: This analysis is generated by an AI system for informational "
            "purposes only. It is NOT a medical diagnosis. All findings must be reviewed "
            "and confirmed by a qualified healthcare professional. Do not make treatment "
            "decisions based solely on this report."
        ),
        "patient_info": {
            "name": patient_info.get("name", "Not available"),
            "age": patient_info.get("age", "Not available"),
            "gender": patient_info.get("gender", "Not available"),
        },
        "summary": {
            "total_tests_extracted": len(lab_values),
            "abnormal_count": len(abnormal_findings),
            "critical_count": sum(1 for f in abnormal_findings if "critical" in f["status"]),
            "insights_generated": len(insights),
            "overall_risk": risk_scores.get("overall", 0),
            "overall_risk_level": risk_scores.get("overall_level", "minimal"),
        },
        "abnormal_findings": abnormal_findings,
        "clinical_concerns": clinical_concerns,
        "differential_diagnosis": differential,
        "risk_scores": risk_scores.get("organ_systems", {}),
        "recommendations": recommendations,
        "all_lab_values": [
            {
                "test": lab.get("test_name", lab.get("canonical_name", "")),
                "value": lab.get("value"),
                "unit": lab.get("unit") or lab.get("expected_unit", ""),
                "status": lab.get("status", "normal"),
                "reference_range": _format_range(lab.get("reference_min"), lab.get("reference_max")),
            }
            for lab in lab_values
        ],
    }

    return report


def format_text_report(report: dict) -> str:
    """
    Format the clinical summary as a plain-text physician-ready report.
    """
    lines = []
    lines.append("╔══════════════════════════════════════════════════════════╗")
    lines.append("║          MEDBIOS AI — PATIENT REPORT ANALYSIS           ║")
    lines.append("╚══════════════════════════════════════════════════════════╝")
    lines.append("")
    lines.append(f"  Generated: {report.get('generated_at', 'N/A')}")
    lines.append(f"  Document Type: {report.get('document_type', 'N/A').replace('_', ' ').title()}")
    lines.append("")

    # Patient info
    pi = report.get("patient_info", {})
    lines.append("─── Patient Information ───")
    lines.append(f"  Name: {pi.get('name', 'N/A')}")
    lines.append(f"  Age: {pi.get('age', 'N/A')}")
    lines.append(f"  Gender: {pi.get('gender', 'N/A')}")
    lines.append("")

    # Summary
    summary = report.get("summary", {})
    lines.append("─── Summary ───")
    lines.append(f"  Tests Extracted: {summary.get('total_tests_extracted', 0)}")
    lines.append(f"  Abnormal Values: {summary.get('abnormal_count', 0)}")
    lines.append(f"  Critical Values: {summary.get('critical_count', 0)}")
    lines.append(f"  Clinical Insights: {summary.get('insights_generated', 0)}")
    lines.append(f"  Overall Risk: {summary.get('overall_risk_level', 'N/A').upper()}")
    lines.append("")

    # Abnormal findings
    findings = report.get("abnormal_findings", [])
    if findings:
        lines.append("─── Key Abnormal Findings ───")
        for f in findings:
            status_icon = "🔴" if "critical" in f["status"] else "🟡" if f["status"] in ("high",) else "🔵"
            ref = f" (ref: {f['reference_range']})" if f["reference_range"] else ""
            lines.append(f"  {status_icon} {f['test']}: {f['value']} {f['unit']} [{f['status'].upper()}]{ref}")
        lines.append("")

    # Clinical concerns
    concerns = report.get("clinical_concerns", [])
    if concerns:
        lines.append("─── Possible Clinical Concerns ───")
        for c in concerns:
            conf_icon = "●" if c["confidence"] == "high" else "◐" if c["confidence"] == "medium" else "○"
            lines.append(f"  {conf_icon} {c['condition']} [{c['confidence'].upper()} confidence]")
        lines.append("")

    # Risk scores
    risk = report.get("risk_scores", {})
    if risk:
        lines.append("─── Organ System Risk Scores ───")
        for system, data in risk.items():
            bar = _risk_bar(data["score"])
            lines.append(f"  {system.title():20s} {bar} {data['score']}% ({data['level']})")
        lines.append("")

    # Recommendations
    recs = report.get("recommendations", [])
    if recs:
        lines.append("─── Recommended Follow-up ───")
        for r in recs:
            priority_icon = "⚡" if r["priority"] == "high" else "→"
            lines.append(f"  {priority_icon} {r['recommendation']}")
            lines.append(f"    Related to: {r['related_to']}")
        lines.append("")

    # Disclaimer
    lines.append("─── IMPORTANT ───")
    lines.append(f"  {report.get('disclaimer', '')}")
    lines.append("")

    return "\n".join(lines)


def _format_range(min_val, max_val) -> str:
    """Format reference range as string."""
    if min_val is not None and max_val is not None:
        return f"{min_val} - {max_val}"
    return ""


def _risk_bar(score: float) -> str:
    """Generate ASCII risk bar."""
    filled = int(score / 10)
    return f"[{'█' * filled}{'░' * (10 - filled)}]"
